settings:
  world-name: "world"
  coordinate-range-x: 1000
  coordinate-range-z: 1000
  schematic-name: "event.schem"
  stages:
    one:
      pvp: false
      duration: 120
      available-abilities:
        - "SPLASH_PUNCH"
      open-chest: false
    two:
      pvp: false
      duration: 120
      available-abilities:
        - "FIREBALL"
      open-chest: false
    three:
      pvp: true
      duration: 120
      available-abilities:
        - "HORSE"
      open-chest: true
  use-abilities: 120 # В тиках
  abilities:
    - "FIREBALL;50"
    - "HORSE;50"
    - "SPIDER_WEB;50"
    - "SPLASH_PUNCH;50"
  mana: 100000
  chests:
    1:
      offset-x: 5
      offset-y: 0
      offset-z: 5
  settings-abilities:
    fireball:
      radius-search-players: 10
      damage: 10
      count-fireball: 10
      boost-y: 3
      offset-location-x: 5
      offset-location-z: 5
      offset-x: 1
      offset-y: 1
      offset-z: 1
      speed: 3
    horse:
      damage: 10
      distance: 3
      num-one: -2
      num-two: 3
      forward-blocks: 3
      speed: 0.2
      knockback-blocks: 3
      later-death: 20
    spider-web:
      radius-search-players: 10
      damage: 1
      radius: 1
      later-remove: 40
    splash-punch:
      damage: 1
      count: 1
      later-count: 2
      radius: 10
      step-radius: 3
      later-forward: 1
      particle-count: 70
      later-forward-particle: 0
      step: 0.5
      radius-search-players: 10
      later-back: 1
      later-back-particle: 0
  hologram-provider: "DECENT_HOLOGRAMS"
  hologram-lines:
    - ""
    - "&bМана: &f%mana%"
    - "&dСтадия: &f%stage%"
    - "&fПоследняя способность: &6%ability%"
    - ""
  chances:
    1:
      material: DIAMOND_SWORD
      chance: 50.0
      # enchantments:
        # - Зачарование;Уровень
  actions-start-event:
    - ""
    - "[broadcast] &fИвент запущен &6%x% %y% %z%"
    - ""
  actions-end-event:
    - ""
    - "[broadcast] &fИвент окончен"
    - ""
  bar-message: "&fКоординаты &6%x% %y% %z% &8| &fСтадия &6%stage% &8| &fОкончание стадии &6%remaining% &8| &fПвп &6%pvp%"
  bar-color: "YELLOW"
  bar-style: "SEGMENTED_12"
  # bar-flags:
    # - Флаг
  plus-mana: 10
  actions-switch-stage:
    - ""
    - "[broadcast] &fСтадия переключена"
    - ""
  type: "Essentials"
  region-flags:
    - "BUILD: DENY"
  plus-mana-stage: 100
