settings:
  colorizer-type: HEX
  world-name: "world"
  coordinate-range-x: 1000
  coordinate-range-z: 1000
  schematic-name: "event.schem"
  teleport: true
  later-air-or-lighting-drop: 480
  stages:
    one:
      pvp: true
      duration: 120
      available-abilities:
        - "SPIDER_WEB"
        - "FIREBALL"
        - "SPLASH_PUNCH"
        - "HORSE"
        - "GLOWING"
      open-chest: false
      air-or-lighting-drop: false
      with-lighting: false
    two:
      pvp: true
      duration: 120
      available-abilities:
        - "SPIDER_WEB"
        - "FIREBALL"
        - "SPLASH_PUNCH"
        - "HORSE"
        - "GLOWING"
      open-chest: false
      air-or-lighting-drop: true
      with-lighting: false
    three:
      pvp: true
      duration: 120
      available-abilities:
        - "SPIDER_WEB"
        - "FIREBALL"
        - "SPLASH_PUNCH"
        - "HORSE"
        - "GLOWING"
      open-chest: true
      air-or-lighting-drop: true
      with-lighting: true
  use-abilities: 120
  abilities:
    - "FIREBALL;50"
    - "HORSE;50"
    - "SPIDER_WEB;50"
    - "SPLASH_PUNCH;50"
    - "GLOWING;50"
  mana: 1000
  chests:
      1:
        offset-x: 9
        offset-y: 1
        offset-z: 15
  settings-abilities:
    fireball:
      radius-search-players: 10
      damage: 15
      count-fireball: 10
      boost-y: 3
      offset-location-x: 5
      offset-location-z: 5
      offset-x: 1
      offset-y: 1
      offset-z: 1
      speed: 3
    horse:
      damage: 15
      distance: 3
      num-one: -2
      num-two: 3
      forward-blocks: 10
      speed: 0.2
      knockback-blocks: 3
      later-death: 60
    spider-web:
      radius-search-players: 10
      damage: 5
      radius: 1
      later-remove: 40
    splash-punch:
      damage: 5
      count: 1
      later-count: 2
      radius: 10
      step-radius: 3
      later-forward: 1
      particle-count: 70
      later-forward-particle: 0
      step: 0.5
      radius-search-players: 10
      later-back: 1
      later-back-particle: 0
    glowing:
      nearby-x: 5
      nearby-y: 5
      nearby-z: 5
      duration: 100
  type: "Essentials"
  hologram-provider: "DECENT_HOLOGRAMS"
  bar-color: "YELLOW"
  bar-style: "SEGMENTED_12"
  plus-mana: 100
  plus-mana-stage: 1000
  region-flags:
    - "BUILD: DENY"
  boost-y: 15
  count-drops: 5
  cooldown-taking-an-item: 100